// OSM Client Monitoring Data Types & Storage

export type ClientMonitoringStatus = "Activo" | "Inactivo" | "Investigar" | "Visita Tecnica" | "Sin monitoreo" | "Linea Telefonica" | "Safe y Kronos" | "Suspendido" | "Sin notificaciones" | "Sin sistema" | "Prueba";
export type ClientResolutionStatus = "Pendiente" | "Resuelto";
export type SystemStatus = "Encendido" | "Apagado" | "Suspendido" | "Inactivo" | "Prueba";
export type BillingConfirmation = "Activa" | "Inactiva" | "Inaviva" | "No existe";

export interface OSMClient {
  id: string;
  accountCode: string;
  businessName: string;
  contact: string;
  phone: string;
  monitoringStatus: ClientMonitoringStatus;
  resolutionStatus: ClientResolutionStatus;
  notes: string;
  systemName?: string;
  systemStatus?: SystemStatus;
  billingClient?: string;
  billingDescription?: string;
  billingEmail?: string;
  billingArticle?: string;
  hasBilling: boolean;
  lastUpdated: string;
  updatedBy?: string;
}

const STORAGE_KEY = "osm_clients_data";
const SEED_VERSION_KEY = "osm_clients_seed_v";
const CURRENT_SEED = 5;

function generateId(): string {
  return "OSM-" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

// Complete seed from all data sources: system inventory, incidents, billing (CxC), and client reviews
function getInitialData(): OSMClient[] {
  const d = "2026-04-08";
  return [
    // ── INCIDENCIAS (con datos de contacto y notas detalladas) ──
    { id: generateId(), accountCode: "8003", businessName: "FARMAMED", contact: "", phone: "809-977-1644", monitoringStatus: "Visita Tecnica", resolutionStatus: "Pendiente", notes: "La chica necesita una visita tecnica para revisar un sensor", hasBilling: true, billingClient: "LABORATORIOS FARMAMED DOMINICANA, SRL", billingEmail: "laboratoriosfd@hotmail.com", billingDescription: "Servicio de Monitoreo Básico", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2484", businessName: "GRUPO JARDINES ILUCIONES", contact: "GISELLE MATOS", phone: "809-284-4636", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Se realizo visita tecnica | caso resuelto. No estamos recibiendo alertas ni ninguna notificacion.", hasBilling: true, billingClient: "JARDIN ILUSIONES, SRL", billingEmail: "contabilidad@grupoilusiones.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5488", businessName: "RESIDENCIA CAROLINA HENRIQUEZ", contact: "CAROLINA HENRIQUEZ", phone: "809-880-5964", monitoringStatus: "Investigar", resolutionStatus: "Pendiente", notes: "Seguimiento en kronos, no llegan notificaciones.", hasBilling: true, billingClient: "RES. CAROLINA HENRIQUEZ", billingEmail: "chenriquezr@hotmail.com", billingDescription: "Servicio Monitoreo de Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2007", businessName: "FLAWLESS MAKEUP", contact: "ROLAND", phone: "809-968-5675", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Resuelto. Llevan desde el 29 sin realizar un cierre.", hasBilling: true, billingClient: "FLAWLESS MAKEUP BY LILY MUA EIRL", billingEmail: "flawlessmakeup@gmail.com", billingDescription: "Servicio monitoreo de alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9107", businessName: "JEROME AUTOSERVICES SRL", contact: "NATANAEL JEROME", phone: "809-214-9102", monitoringStatus: "Investigar", resolutionStatus: "Pendiente", notes: "Desde el 2024 sin realizar ninguna actividad en la cuenta.", hasBilling: true, billingClient: "JEROME AUTOSERVICES SRL", billingEmail: "infojeromerd@gmail.com", billingDescription: "Servicio monitoreo de alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "RES. ANA ROSA NUÑEZ", contact: "", phone: "", monitoringStatus: "Sin monitoreo", resolutionStatus: "Pendiente", notes: "No existe en ninguno de los programas de monitoreo.", hasBilling: true, billingClient: "RES. ANA ROSA NUÑEZ", billingEmail: "", billingDescription: "Servicio monitoreo de alarma", lastUpdated: d },
    { id: generateId(), accountCode: "8998", businessName: "R & V AUTO TUNING", contact: "VILMA VARGAS", phone: "829-384-6792", monitoringStatus: "Investigar", resolutionStatus: "Pendiente", notes: "Desde el 2025-8-22 sin realizar un cierre.", hasBilling: true, billingClient: "ROWIL & NICOLE AUTO TUNING SRL", billingEmail: "autotuningrv@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9124", businessName: "CENTRO FERRETERO GRUPO CMA REYES,SRL", contact: "CARLOS MARQUES", phone: "829-771-9756", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Se realizo una visita tecnica el dia 23/03/26 caso resuelto", hasBilling: true, billingClient: "CENTRO FERRETERO C.M.A.", billingEmail: "CARLOSMARQUEZ111973@HOTMAIL.COM", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5398", businessName: "QUICKIE (SR & RN IMPORT SRL)", contact: "STEVE REYNOSO", phone: "809-603-6000", monitoringStatus: "Inactivo", resolutionStatus: "Pendiente", notes: "Problemas con la comunicacion, tenemos tiempo sin recibir ninguna alerta.", hasBilling: true, billingClient: "SR & RN IMPORT SRL", billingEmail: "gllamasb@hotmail.com", billingDescription: "Servicio Monitoreo y Alarma Naco", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8907", businessName: "EDIFICIO LFT (RES. MARISOL CONTRERAS)", contact: "MARI CONTRERAS", phone: "240-370-2519", monitoringStatus: "Investigar", resolutionStatus: "Pendiente", notes: "Desde 29 de enero sin recibir alertas, contactar con el cliente.", hasBilling: true, billingClient: "RES. MARISOL CONTRERAS", billingEmail: "", billingDescription: "Monitoreo Alarma y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "RES. CESAR ALEXANDER CRUZ", contact: "", phone: "", monitoringStatus: "Sin monitoreo", resolutionStatus: "Pendiente", notes: "No aparece en ninguna de las aplicaciones de monitoreo.", hasBilling: true, billingClient: "RES. CESAR ALEXANDER CRUZ", billingEmail: "", billingDescription: "Servicio Monitoreo y Alarma", lastUpdated: d },
    { id: generateId(), accountCode: "8918", businessName: "RAPID PACK", contact: "", phone: "809-973-7143", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Se realizo una visita tecnica | caso resuelto", hasBilling: true, billingClient: "AM SK CARG LOGIST LA MENSAJERIA SRL (RAPID PACK)", billingEmail: "alexanderduarte3@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8997", businessName: "GRUPO VE+58", contact: "RAFAEL PEREZ", phone: "849-212-1919", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "GRUPO VE + 58 SRL", billingEmail: "ggarciasoft@gmail.com", billingDescription: "Plan Alarma + Camara", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5481", businessName: "JEAN LICORES", contact: "JUAN CARLOS SERRATA", phone: "829-357-6735", monitoringStatus: "Investigar", resolutionStatus: "Pendiente", notes: "El sistema no nos llegan las alertas correctamente", hasBilling: true, billingClient: "JEAN LICORES JCS SRL", billingEmail: "juancarlos2684@hotmail.com", billingDescription: "SERVICIO DE MONITOREO ALARMAS", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "RES. GREGORY GARCIA", contact: "", phone: "", monitoringStatus: "Safe y Kronos", resolutionStatus: "Pendiente", notes: "No aparece en ninguna de las aplicaciones de monitoreos, no tiene ningun rastro.", hasBilling: false, lastUpdated: d },
    { id: generateId(), accountCode: "5393", businessName: "RESIDENCIA CLEIDY", contact: "CLEIDY JULIANA", phone: "809-780-5302", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Se realizo visita tecnica | Caso resuelto. Reporto problemas con la bateria.", hasBilling: true, billingClient: "CLEIDY JULIANA LORENZO LORA", billingEmail: "LORENZOCLEIDY@GMAIL.COM", billingDescription: "Servicio Monitoreo Alarmas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "RAINERI JONAS MARTIN FRIAS", contact: "", phone: "", monitoringStatus: "Sin monitoreo", resolutionStatus: "Pendiente", notes: "Necesitamos mas informacion para identificarla en el sistema.", hasBilling: true, billingClient: "RAINERI JONAS MARTIN FRIAS", billingEmail: "Rainerimartin49@gmail.com", billingDescription: "PLAN SISTEMA MONITOREO ALARMA", lastUpdated: d },
    { id: generateId(), accountCode: "8653", businessName: "JAN SRL", contact: "XIOMARA MORET", phone: "849-353-1431", monitoringStatus: "Visita Tecnica", resolutionStatus: "Pendiente", notes: "Problemas con la comunicacion, no nos aparece las alertas de aperturas y cierres.", hasBilling: true, billingClient: "JAN, S.R.L.", billingEmail: "contabilidad@almalum.com", billingDescription: "PLAN SISTEMA DE ALARMA- SAN PEDRO", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "4012", businessName: "TOPCAR DETAIL", contact: "OSCAR PANIAGUA", phone: "829-828-1493", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Se realizo visita tecnica | caso resuelto. Se le olvida algunas veces cerrar.", hasBilling: true, billingClient: "TOPCAR BY LCP GROUP SRL", billingEmail: "TOPCAR.RD18@GMAIL.COM", billingDescription: "Monitoreo de Alarmas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "4013", businessName: "SOBREMESA", contact: "ERICK FLORES", phone: "809-980-0949", monitoringStatus: "Investigar", resolutionStatus: "Pendiente", notes: "Lleva 1 mes sin realizar el cierre.", hasBilling: true, billingClient: "SOBREMESA EMPRESARIAL Y CATERING, SRL", billingEmail: "hola@sobremesard.com", billingDescription: "Plan Monitoreo de Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8001", businessName: "Residencia - Alba Yris Santos", contact: "ALBA YRIS SANTOS", phone: "809-383-9888", monitoringStatus: "Investigar", resolutionStatus: "Pendiente", notes: "Lleva mas de 15 dias sin realizar un cierre.", hasBilling: true, billingClient: "PATRIA ALBA YRIS", billingEmail: "albayrissantos@gmail.com", billingDescription: "Plan Monitoreo de Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8989", businessName: "YUYAX SRL", contact: "Xavier Alcantara", phone: "809-357-6613", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Se realizo visita tecnica caso resuelto.", hasBilling: true, billingClient: "YUYAX SRL", billingEmail: "Xavieralcantarac@gmail.com", billingDescription: "Sistema Monitoreo Alarma y Cámara", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5895", businessName: "FERRETERIA ARENERA C&M", contact: "ALBA CASTRO", phone: "849-353-4552", monitoringStatus: "Suspendido", resolutionStatus: "Pendiente", notes: "Suspendido temporalmente, esperando actualizacion con las facturas.", hasBilling: false, systemStatus: "Suspendido", lastUpdated: d },
    { id: generateId(), accountCode: "2010", businessName: "COCHES RD", contact: "Cesar Tronillo", phone: "(849) 220-9390", monitoringStatus: "Inactivo", resolutionStatus: "Pendiente", notes: "El monitoreo es via telefonica y estamos teniendo problemas con las alarmas.", hasBilling: true, billingClient: "RES. CESAR TRONILO", billingEmail: "cochesrd@gmail.com", billingDescription: "Servicio monitoreo alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "1000", businessName: "CASECOR", contact: "Caraballo", phone: "(829) 521-1490", monitoringStatus: "Linea Telefonica", resolutionStatus: "Pendiente", notes: "No estamos recibiendo alertas.", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2496", businessName: "Toro Business Catalys SRL AV Romulo Betancourt", contact: "", phone: "809-330-6969", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Se realizo una visita tecnica 01-04-26. Resuelto.", hasBilling: true, billingClient: "TORO BUSINESS CATALYST SRL", billingEmail: "afamilia@toro.com.do", billingDescription: "Servicio Monitoreo y Alarma BELLA VISTA", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "4010", businessName: "MAPACA", contact: "", phone: "849-285-1287", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Resuelto. Lleva 7 dias sin cerrar.", hasBilling: true, billingClient: "MAPACA DIGITAL GROUP EIRL", billingEmail: "mcdigitalrd@gmail.com", billingDescription: "Monitoreo 24/7 Asistencia de Seguridad", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "Residencia Ivette Haddad", contact: "", phone: "(809) 919-2552", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "Se realizo visita tecnica caso resuelto. Tiene un pitito constante y no coge la alarma.", hasBilling: false, lastUpdated: d },

    // ── SISTEMA INVENTARIO (Resumen) - clientes no incluidos arriba ──
    { id: generateId(), accountCode: "0078", businessName: "JADE TERIYAKI - PLAZA BAVARO CITY CENTER", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma - Bavaro City", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "0204", businessName: "Tree house 2", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "TREEHOUSE SRL", billingEmail: "office@treehousedr.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "1001", businessName: "CAMARA DE COMERCIO Y PRODUCCION", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "CAMARA DE COMERCIO Y PRODUCCION DE SANTO DOMINGO", billingEmail: "ihernandez@camarasantodomingo.do", billingDescription: "Servicio de Monitoreo de alarma y respuesta armada 24/7", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "1549", businessName: "RESIDENCIA ANIBAL GUZMAN", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "1838", businessName: "RES. GEOVANNA RODRIGUEZ", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "RES. GEOVANNA RODRIGUEZ", billingEmail: "ing_teresitarodriguez@hotmail.com", billingDescription: "Servicio Monitoreo de Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "1924", businessName: "LEGION XXXIII", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "1932", businessName: "Vape Crew - Almacen (Ensanche Ozama)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "PE DISTRIBUTION EIRL (VAPE CREW)", billingEmail: "s.peynado02@gmail.com", billingDescription: "Servicio Monitoreo Alarma-Almacen Ensanche Ozama", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2001", businessName: "LUIS MANUEL AGUILO (OFICINA)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "LUIS MANUEL AGUILO, SRL", billingEmail: "adm.contabilidadlumasa@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2002", businessName: "DC NATIONAL CALL CENTER CARIBE", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "2004", businessName: "LUNIFRAN (Pendiente Retirar LX)", contact: "", phone: "", monitoringStatus: "Inactivo", resolutionStatus: "Resuelto", notes: "No llamar. Retiro el servicio.", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "2009", businessName: "Pharmatech - Almacen", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "Pharmaceutical Tecnology", billingEmail: "WGONZALEZ@PHARMATECH.COM.DO", billingDescription: "Servicio monitoreo de alarma-Almacen", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2019", businessName: "Jade Teriyaki - Jumbo (Luperon)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma- Suc. Jumbo Luperón", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2020", businessName: "Jade Teriyaki - Carretera Mella", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarmas-Carretera Mella", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2222", businessName: "OFICINA PRINCIPAL SAFEONE", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2312", businessName: "JA INVESTMENT ANTIG RD SRL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JA INVESTMENT ANTIG RD SRL", billingEmail: "INFO@INVERSIONESANTIGUARD.COM", billingDescription: "Servicio Monitoreo de Alarmas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2439", businessName: "Tree house 1", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "TREEHOUSE SRL", billingEmail: "office@treehousedr.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2473", businessName: "Jade Teriyaki - Plaza Charles De Gaulle", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios Monitoreo de Alarma- Suc. Charles de Gaulle", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2480", businessName: "JAQUELINE LUCIANO", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "2507", businessName: "RESIDENCIA SRA.YOCASTA", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "2509", businessName: "MR TECH ALMACEN", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "MAREDO TECH SRL", billingEmail: "reynoso2323@hotmail.com", billingDescription: "Servicio monitoreo de Alarma-Almacen", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2514", businessName: "XIOPE", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "DISTRIBUIDORA XIOPED, S.R.L.", billingEmail: "p.jrodriguez@hotmail.com", billingDescription: "Servicio de monitoreo de alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "2710", businessName: "Jade teriyaki - Restaurante santiago", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "EXPRESO JADE SRL", billingEmail: "contabilidad@expresojade.com", billingDescription: "Servicio de Monitoreo Alarma- Santiago", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "3373", businessName: "Jade Teriyaki Agora Santiago", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarmas- Suc. Agora Santiago", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "3375", businessName: "RESIDENCIA LIZMARLIN DE LEON", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "D LEON CONSULTING SRL", billingEmail: "npena@dleonconsultingrd.com", billingDescription: "Servicio Monitoreo Alarma- Residencial", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "3493", businessName: "Betcris 27 (Panel incendio 2)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "3896", businessName: "Baston 3896", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "4011", businessName: "Mr tech 27 de febrero", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "4014", businessName: "Olympus Tech", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "4016", businessName: "ASPRO", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "YUYAX SRL / AVALUOS Y SERVICIOS DE PROPIEDADES ASPRO", billingEmail: "Xavieralcantarac@gmail.com;inversionesfacil@gmail.com", billingDescription: "Sistema Monitoreo Alarma y Cámara (Almacen) ASPRO", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "4090", businessName: "Jade Teriyaki Plaza Internacional", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma - Santiago Plaza Internacional", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "4311", businessName: "Jade Teriyaki (Churchill)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5395", businessName: "FERRETERIA EL VIGIA", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5410", businessName: "CASA DE LEYLANI HERNANDEZ", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "LEYLANI ESTHER HERNANDEZ MARTINEZ", billingEmail: "lani.hdez@gmail.com", billingDescription: "SERVICIO DE MONITOREO ALARMAS", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5411", businessName: "VILLA MARLON", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5412", businessName: "RESIDENCIA DE LA SRA. GIOVANNA TERESITA", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5413", businessName: "PAGINAS BBDO", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "PAGES BBDO SRL", billingEmail: "cindy.lopez@ex4cto.com", billingDescription: "Servicio Monitoreo y Alarma (Paginas BBDO)", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5475", businessName: "Betcris - San Francisco", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-San Francisco", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5476", businessName: "LRT BEGOVI", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BEGOVI SRL", billingEmail: "TICOBERAS@HOTMAIL.COM", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5478", businessName: "OMD", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "INMOBILIARIA COLE SRL (OMD)", billingEmail: "lisselot.guerrero@ex4cto.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5479", businessName: "LONCIN", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "MOTORES DEL SUR (LONCIN)", billingEmail: "I.DELACRUZ@MOTORESDELSUR.COM", billingDescription: "Servicio de monitoreo 24/7", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5490", businessName: "DC NATIONAL CALL CENTER CARIBE (2)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "5501", businessName: "RESIDENCIA FERNANDO CRESPO (CIMADEVILLA)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "CIMADEVILLA SRL", billingEmail: "sjoa@galeria360.com.do", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "5505", businessName: "Jade Teriyaki - Bravo Las Americas", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo Alarmas - BRAVO LAS AMERICAS", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5849", businessName: "Betcris 27 (Panel incendio 1)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5851", businessName: "Jade teriyaki -- Agora mall", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios Monitoreo de Alarma- Suc.Agora Mall", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5852", businessName: "Jade Teriyaki - Arroyo Hondo", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma- CAMINO CHIQUITO", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5853", businessName: "Jade Teriyaki - Plaza Roman", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma - PLAZA ROMAN", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5854", businessName: "URBAN GROUP", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "URBANGROUP SOLUTIONS", billingEmail: "administracion@urbangrouprd.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5855", businessName: "PRALINE", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "PRALINE CATERERS & BAKERY SRL", billingEmail: "Praline.rd@gmail.com", billingDescription: "Servicios de Monitoreo Alarmas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5856", businessName: "NUEVA EXP.", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "5857", businessName: "LX sin instalar", contact: "", phone: "", monitoringStatus: "Inactivo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "5859", businessName: "EXP.", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "5861", businessName: "PLAZA VDI DIAZSOFT", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "DIAZSOFT TECHNOLOGY SRL", billingEmail: "jmateo@diazsoft.com.do", billingDescription: "Servicio monitoreo de Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5862", businessName: "Jade Teriyaki - Terranova", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma- PLAZA TERRANOVA", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5863", businessName: "Betcris 27 (Panel incendio 3)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5867", businessName: "Jade Teriyaki - Plaza Paseo 27", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios Monitoreo de Alarma- Plaza Paseo 27", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5868", businessName: "Jade Teriyaki - Plaza Cuadra", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios Monitoreo de Alarma- Plaza Cuadra", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5869", businessName: "1A Eventos", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "No cuenta con el servicio de monitoreo activo", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5870", businessName: "BARKING MOMENTS PHOTOGRAFHY", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BARKING MOMENTS PHOTOGRAPHY SRL", billingEmail: "info@barkingmomentsrd.com", billingDescription: "Servicio de Monitoreo Alarmas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5873", businessName: "Jade Teriyaki - Maximo Gomez", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma- PLAZA EL FARO", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5874", businessName: "Jade Restaurant - Naco", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "EXPRESO JADE SRL", billingEmail: "contabilidad@expresojade.com", billingDescription: "Servicio de Monitoreo Alarma- AV. 27 Febrero (NACO)", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5877", businessName: "FIOCHI", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "5879", businessName: "BM CARGO COLINA DE LOS RIOS (PINANA INDUSTRIAL)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "PINANA AGROINDUSTRIAL SRL", billingEmail: "pinanabmc@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5880", businessName: "NAVE RICO MELAO", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "RICO MELAO DOMINICANA SRL", billingEmail: "ricomelaoventas@gmail.com", billingDescription: "Servicios de Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5882", businessName: "JOSE ARMENTEROS Y Co. (Almacen)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JOSE ARMENTEROS & Co.", billingEmail: "bsosa@jaco.com.do", billingDescription: "Servicio de monitoreo de alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5883", businessName: "MR TECH TIENDA", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "MAREDO TECH SRL", billingEmail: "reynoso2323@hotmail.com", billingDescription: "Servicio monitoreo de Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5884", businessName: "MK PUNTO SMART", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5885", businessName: "Jade Teriyaki Colinas Mall", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma - Santiago Colinas Mall", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5888", businessName: "Jade Restaurante - Sambil", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "EXPRESO JADE SRL", billingEmail: "contabilidad@expresojade.com", billingDescription: "Servicios Monitoreo de Alarma- Sambil", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5889", businessName: "RESIDENCIA MARIA CARCAÑO", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "MARIA ELIZABETH CALCAÑO ESCOFET", billingEmail: "meescofet@hotmail.com", billingDescription: "Servicio de Monitoreo Alarmas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5890", businessName: "HESETEC.", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "CHECKSTAND SERVICIOS TECNICOS EIRL", billingEmail: "j.nieves@chesetec.com", billingDescription: "Servicio de Monitoreo de Alarmas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5891", businessName: "FERRETERIA BRIANNA", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "FERRETERIA BRIANA", billingEmail: "Jyrmuebles@gmail.com", billingDescription: "Servicios de Monitoreo Alarmas", systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "5893", businessName: "SERVI CENTRO ALMACEN", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5894", businessName: "Jade Teriyaki - Gazcue", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarmas- AV. INDEPENDENCIA (GAZCUE)", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5896", businessName: "Pharmatech - Almacen 2", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "Pharmaceutical Tecnology", billingEmail: "WGONZALEZ@PHARMATECH.COM.DO", billingDescription: "Servicio monitoreo de alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5898", businessName: "Jade teriyaki nuñez de caceres", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma- Suc. Nuñez de Caceres", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "5899", businessName: "Sweet and Bite", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "ASSET ENTERPRISE SRL", billingEmail: "emercedes@asset.com.do", billingDescription: "Servicio monitoreo de alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "6118", businessName: "BESTHINGH MUSIC ADORNOS SRL.", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BESTHIGH MUSIC AUTOADORNOS", billingEmail: "Ar1audio@gmail.com", billingDescription: "Servicio de Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "6134", businessName: "RESIDENCIAL LERESA III", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "6880", businessName: "SERVI CENTRO", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "SERVINET CENTRO DE SERVICIOS SRL", billingEmail: "mksmartshop1@gmail.com", billingDescription: "Servicio monitoreo de alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "6891", businessName: "Pala pizza", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "INVERSIONES GUSTAINO", billingEmail: "Info.gustaino@gmail.com", billingDescription: "Servicio de Monitoreo Básico", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "7632", businessName: "Hik prueba", contact: "", phone: "", monitoringStatus: "Prueba", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "7658", businessName: "TEST V2", contact: "", phone: "", monitoringStatus: "Prueba", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "7800", businessName: "TEST LX", contact: "", phone: "", monitoringStatus: "Prueba", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8004", businessName: "Little Caesars - LCPZ Dominican Republic, SRL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "LCPZ DOMINICAN REPUBLIC SRL", billingEmail: "dcruz@pcsapi.com", billingDescription: "Plan Monitoreo de Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8005", businessName: "Mas Technology", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8085", businessName: "Prueba", contact: "", phone: "", monitoringStatus: "Prueba", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8095", businessName: "Jade Teriyaki - Plaza Duarte (Carrefour)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicio Monitoro de Alarma- Plaza Duarte", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8125", businessName: "Merkanti SRL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "MERKANTI SRL", billingEmail: "merkanti.srl@gmail.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8258", businessName: "Jade Teriyaki - Plaza Friusa Nv", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma - Bavaro Friusa", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8511", businessName: "Little Caesars Pizza - Autopista Duarte", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8514", businessName: "Jade teriyaki (Puerto plata)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarmas- Suc.Puerto Plata", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8515", businessName: "Pala pizza (Naco)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8614", businessName: "Betcris - Malecon", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma- Av.George Washington", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8624", businessName: "Jade Teriyaki - San Vicente", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarmas- SUC. SAN VICENTE DE PAUL", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8634", businessName: "NEGOCIO DE ANA HERNANDEZ", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Pendiente", notes: "", hasBilling: true, billingClient: "RES. ANA HERNANDEZ", billingEmail: "", billingDescription: "Servicio Vigilancia de Cámara", systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8640", businessName: "REPLAY RENT STORE", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "REALY RENT STORE", billingEmail: "nicole.1415@hotmail.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8641", businessName: "RESIDENCIA RACHEL AGRAMONTE", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8642", businessName: "ECONOMARKET LA PISTA", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8644", businessName: "Betcris - Sabana Larga", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Sabana Larga", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8645", businessName: "Betcris - Almacen", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma- Almacen", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8647", businessName: "D´TORD", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "D'TO RD TECH STORE", billingEmail: "dtord1991@gmail.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8650", businessName: "Betcris - Romana", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-La Romana", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8654", businessName: "FUNDACION DOMINICANA DE CIEGOS", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "FUNDACION DOMINICANA DE CIEGOS INC", billingEmail: "fudci84@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8655", businessName: "Betcris - Bani", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Suc, Bani", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8656", businessName: "ALMALUM", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "EL ALMACEN DEL ALUMINIO ALMALUM SRL", billingEmail: "contabilidad@almalum.com", billingDescription: "PLAN SISTEMA DE ALARMA- STO. DGO.", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8661", businessName: "LA PLAZA DEL MUEBLE", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8727", businessName: "Pharmatech", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "Solamente funciona esta cuenta de Pharmatech", hasBilling: true, billingClient: "Pharmaceutical Tecnology", billingEmail: "WGONZALEZ@PHARMATECH.COM.DO", billingDescription: "Servicio monitoreo de alarma-Oficina Principal", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8735", businessName: "Jade teriyaky - Nine Mall", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios Monitoreo de Alarma- Plaza Nine Mall", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8751", businessName: "RESIDENCIA GRECIA BRUGAL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "RES. GRECIA NINOSKA BRUGAL", billingEmail: "greciabrugal@gmail.com", billingDescription: "Servicio monitoreo de alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8895", businessName: "BENNY STORE", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BENNY STORE", billingEmail: "bennystorerd@gmail.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8897", businessName: "KAIROS IMPORT,SRL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "KAIROS IMPORT SRL", billingEmail: "l.baez@kairosimportrd.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8899", businessName: "Betcris - Santiago", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma Suc. Santiago", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8900", businessName: "PUERTO HSRD", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8901", businessName: "MAYA COMERCIAL SRL.", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8903", businessName: "Jade Teriyaki - Plaza Moderna (San Isidro)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicios de Monitoreo de Alarma- SAN ISIDRO", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8905", businessName: "MOTO REPUESTO CESAR", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8906", businessName: "A & F COMERCIAL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "A&F COMERCIAL FARIMI SRL", billingEmail: "frivas_23@hotmail.com;ayfcomercial03@gmail.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8908", businessName: "Vape Crew - Logistic", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "PE DISTRIBUTION EIRL (VAPE CREW)", billingEmail: "s.peynado02@gmail.com", billingDescription: "Servicio Monitoreo Alarma-Almacén", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8909", businessName: "RESIDENCIA CARMEN PEREZ", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8913", businessName: "TORO BUSINESS CATALYST SRL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "TORO BUSINESS CATALYST SRL", billingEmail: "afamilia@toro.com.do", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8914", businessName: "Betcris - Novo Centro (Oficina Principal)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma- Suc. Oficina Administrativa.", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8915", businessName: "Grupo Cerro Alto", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "GRUPO CERRO ALTO SRL", billingEmail: "grupocerroalto@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8916", businessName: "JDPTECH", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JDP TECH", billingEmail: "ing.perezcuevas@hotmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8917", businessName: "PUEBA NUEVA", contact: "", phone: "", monitoringStatus: "Prueba", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8940", businessName: "IMBELCON SRL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8974", businessName: "LX sin instalar (2)", contact: "", phone: "", monitoringStatus: "Inactivo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8975", businessName: "Betcris - Arroyo Hondo", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Suc. Arroyo Hondo", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8976", businessName: "Vape Crew - Ensanche Ozama", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "PE DISTRIBUTION EIRL (VAPE CREW)", billingEmail: "s.peynado02@gmail.com", billingDescription: "Servicio Monitoreo Alarma-Ensanche Ozama", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8978", businessName: "RESIDENCIA PRISCILA HERNANDEZ", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "8979", businessName: "JDF AUTO PARTS", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JDF AUTO PARTS", billingEmail: "jdfautoparts@claro.net.do", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8983", businessName: "RESIDENCIA HENRRY GONZALEZ", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8984", businessName: "Betcris - Av. 27 De Febrero", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Suc. Av. 27 de Febrero", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8985", businessName: "RESIDENCIA PUJOLS", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "RES. RAISA DE PUJOLS", billingEmail: "raisadepujols@hotmail.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8988", businessName: "TG INFORMATICA VENEZUELA", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "TG COMPUTER SRL", billingEmail: "contabilidad@tgcomputer.net", billingDescription: "Servicio Monitoreo Alarma- AV. VENEZUELA", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8990", businessName: "Betcris - Pueblo Nuevo (San Cristobal)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Suc. Pueblo Nuevo San Cristobal", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8991", businessName: "My Healing Space", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "MY HEALING SPACE SRL", billingEmail: "info@myhealingspacerd.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8993", businessName: "BENUA IMPORTACION SRL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BENUA IMPORT SRL", billingEmail: "benua55@hotmail.com", billingDescription: "Servicio de Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8994", businessName: "WILLI DENTAL", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "WILLY DENTAL SRL", billingEmail: "willydentalrd@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8995", businessName: "RESIDENCIA VANESA", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "RES. VANESSA FRIAS", billingEmail: "vfrias69@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "8996", businessName: "(GOMEZO) CENTRO DE SERVICIOS AUTOMOTRIZ", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "CENTRO DE SERVICIOS GOMEZO SRL", billingEmail: "CENTROGOMEZO@GMAIL.COM", billingDescription: "Servicios de Monitoreo Alarmas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9077", businessName: "RESIDENCIA RAISA FOSTIER", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "RES. RAYSA FOSTIER GUERRERO", billingEmail: "alacroix@toro.com.do", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9104", businessName: "Betcris - Bavaro", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Suc. Bavaro", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9105", businessName: "RESIDENCIA DIGNA FERNANDEZ", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "RES. DIGNA FERNANDEZ", billingEmail: "fernandez.milqueya@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9108", businessName: "Betcris - Charles De Gaulle", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Suc. Charles De Gaulle", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9109", businessName: "COLMADO NOAH", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "SUPER COLMADO MINI MARKET NOAH", billingEmail: "marvinherrera91115@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9110", businessName: "RESIDENCIA LAURA TRINIDAD", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "9111", businessName: "EL RANCHO CHICHARRON Y PARRILLADA", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "9112", businessName: "TECNOLOGIA CARPER", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "CARPER TECHNOLOGY SRL", billingEmail: "juanramonperezcuevas@gmail.com", billingDescription: "Servicio monitoreo de alarma-Casa", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9113", businessName: "ADECOVA", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "ASOCIACION DE COMERCIANTES DETALLISTAS DE VILLAS AGRICOLAS ADECOVA", billingEmail: "guidofernandez15@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9114", businessName: "TREE TOWER LUX", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9116", businessName: "Betcris - Higuey", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Suc. Higuey", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9117", businessName: "DMEDIA GROUP SRL", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "D MEDIA GROUP SRL", billingEmail: "ososam@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "9118", businessName: "RESIDENCIA LUCIANO", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "RES. KARLA LUCIANO", billingEmail: "karlalucisu@gmail.com", billingDescription: "Servicio Monitoreo Alarma", systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "9119", businessName: "IL GIARDINO", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9120", businessName: "CLINICA TARRAZO", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "CONSULTORIO TARRAZO SRL", billingEmail: "administracionrd@clinicatarrazo.com", billingDescription: "Servicio Monitoreo y Alarma", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9121", businessName: "ALMACEN TG COMPUTER", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "TG COMPUTER SRL", billingEmail: "contabilidad@tgcomputer.net", billingDescription: "Servicio Monitoreo Alarma-SAN ISIDRO", systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "9123", businessName: "Vape Crew - El Millon", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "PE DISTRIBUTION EIRL (VAPE CREW)", billingEmail: "s.peynado02@gmail.com", billingDescription: "Servicio Monitoreo Alarma-El Millon", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9125", businessName: "Residencia - Aurelio Perez", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9126", businessName: "Betcris - Madre Vieja (San Cristobal)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "BETCRIS BANCA DE APUESTA SRL", billingEmail: "Cuentasporpagardr@betcris.com", billingDescription: "Servicio Monitoreo y Alarma-Suc. Madre Vieja San Cristobal", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "9127", businessName: "Jade Restaurant - Av. Romulo Betancourt", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "EXPRESO JADE SRL", billingEmail: "contabilidad@expresojade.com", billingDescription: "Servicio de Monitoreo Alarma- Romulo Betancourt", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "336554", businessName: "Nine Mall - Baston", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicio de Rondas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "1102328", businessName: "PRUEBA XP MINIPROG2", contact: "", phone: "", monitoringStatus: "Prueba", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Inactivo", lastUpdated: d },
    { id: generateId(), accountCode: "AT-329902", businessName: "Pharmatech - Baston Almacen", contact: "", phone: "", monitoringStatus: "Sin notificaciones", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "Pharmaceutical Tecnology", billingEmail: "WGONZALEZ@PHARMATECH.COM.DO", billingDescription: "Servicio Active Track-Almacen", systemStatus: "Inactivo", lastUpdated: d },
    { id: generateId(), accountCode: "AT-334031", businessName: "Pages Solis - Baston Entrada La Cuaba", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "PAGES SOLIS INMOBILIARIA, SRL", billingEmail: "luisar@pasoinmobiliaria.com", billingDescription: "Servicio Active Track-Betania", systemStatus: "Apagado", lastUpdated: d },
    { id: generateId(), accountCode: "AT-334033", businessName: "GALBRAITH CORPORATION - BASTON 01", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "AT-334129", businessName: "Supervisor Euripides Frias (Transfertec Ing)", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "AT-334134", businessName: "City Storage - Baston", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "CITY STORAGE SOLUTION SRL", billingEmail: "soporte@citystorage.do", billingDescription: "Servicio de Active Track", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "AT-335956", businessName: "Bethania Solis Inmobiliaria - Baston", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Inactivo", lastUpdated: d },
    { id: generateId(), accountCode: "AT-335960", businessName: "BASTON-SPIRIT NAVE B6", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "SERVICIOS DE GUARDIANES INDUSTRIALES, SRL", billingEmail: "n.suncar@seguinsa.com.do", billingDescription: "Servicio de Monitoreo", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "AT-335968", businessName: "Pages - Baston 6 De Noviembre", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: false, systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "AT-336510", businessName: "BASTON-NAVE A18", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "SERVICIOS DE GUARDIANES INDUSTRIALES, SRL", billingEmail: "n.suncar@seguinsa.com.do", billingDescription: "Servicio de Monitoreo", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "AT-336513", businessName: "Jade Administrativo - Baston", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "JADE TERIYAKI S A", billingEmail: "contabilidad@expresojade.com;igarcia@ninemall.do", billingDescription: "Servicio de Rondas", systemStatus: "Encendido", lastUpdated: d },
    { id: generateId(), accountCode: "AT-336563", businessName: "BASTON-NAVE A3", contact: "", phone: "", monitoringStatus: "Activo", resolutionStatus: "Resuelto", notes: "", hasBilling: true, billingClient: "SERVICIOS DE GUARDIANES INDUSTRIALES, SRL", billingEmail: "n.suncar@seguinsa.com.do", billingDescription: "Servicio de Monitoreo", systemStatus: "Encendido", lastUpdated: d },

    // ── Clientes solo en CxC / revisiones sin cuenta en sistema ──
    { id: generateId(), accountCode: "", businessName: "GRANJA JOCELYN SRL", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "Inactiva en sistema. Eliminar del sistema. Enviar personal tecnico a revision.", hasBilling: true, billingClient: "GRANJA JOCELYN SRL", billingEmail: "contabilidad@granjajocelyn.com", billingDescription: "Servicio de monitoreo de Alarma", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "FUNDACION EDUCATIVA BENDICION FEB INC", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en ninguno de los sistemas.", hasBilling: true, billingClient: "FUNDACION EDUCATIVA BENDICION FEB INC", billingEmail: "rsoliz@mb-rd.org", billingDescription: "Servicio de monitoreo de alarma", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "RES. GUAYACANES", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en ninguno de los sistemas.", hasBilling: true, billingClient: "RES. GUAYACANES", billingEmail: "rodridds@msn.com", billingDescription: "Servicio Monitoreo Alarma", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "DATALINK NETWORKS S.R.L", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en ninguno de los sistemas.", hasBilling: true, billingClient: "DATALINK NETWORKS S R L", billingEmail: "Brigitte.neder@datalink.do;Finanzas@datalink.do", billingDescription: "Servicio monitoreo de alarma", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "KELVIN MOISES MARTINEZ VILLAR", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "Necesitamos mas informacion para confirmar.", hasBilling: true, billingClient: "KELVIN MOISES MARTINEZ VILLAR", billingEmail: "kelvinmoisesmartinez@hotmail.com", billingDescription: "Servicio Monitoreo Alarma", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "MARIA LOPEZ SANCHEZ", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "Encontramos una Maria Lopez en Servi Centro.", hasBilling: true, billingClient: "MARIA LOPEZ SANCHEZ", billingEmail: "servicentrostar@gmail.com", billingDescription: "Servicio de Monitoreo + Almacen", lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "CONDOMINIO TORRE HIPOTECARIA", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en sistema.", hasBilling: false, lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "DESECHABLES M G SRL", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en sistema.", hasBilling: false, lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "FCG AUTO ACCESORIOS", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en sistema.", hasBilling: false, lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "TORRE ARYA", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en sistema.", hasBilling: false, lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "CELESTE DE VERAS", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en sistema.", hasBilling: false, lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "SERVINET CENTRO DE SERVICIOS SRL (Rev)", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en revision 1.", hasBilling: false, lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "CONDOMINIO URBANA ARROYO HONDO", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en sistema.", hasBilling: false, lastUpdated: d },
    { id: generateId(), accountCode: "", businessName: "EMAPAN SP SERVICIOS TECNICOS SRL", contact: "", phone: "", monitoringStatus: "Sin sistema", resolutionStatus: "Pendiente", notes: "No existe en sistema.", hasBilling: false, lastUpdated: d },
  ];
}

export function getOSMClients(): OSMClient[] {
  const seedVersion = localStorage.getItem(SEED_VERSION_KEY);
  const stored = localStorage.getItem(STORAGE_KEY);

  if (!stored || seedVersion !== String(CURRENT_SEED)) {
    const initial = getInitialData();
    localStorage.setItem(STORAGE_KEY, JSON.stringify(initial));
    localStorage.setItem(SEED_VERSION_KEY, String(CURRENT_SEED));
    return initial;
  }

  return JSON.parse(stored);
}

export function saveOSMClients(clients: OSMClient[]): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(clients));
}

export function addOSMClient(client: Omit<OSMClient, "id">): OSMClient {
  const clients = getOSMClients();
  const newClient: OSMClient = { ...client, id: generateId() };
  clients.push(newClient);
  saveOSMClients(clients);
  return newClient;
}

export function updateOSMClient(id: string, updates: Partial<OSMClient>): void {
  const clients = getOSMClients();
  const idx = clients.findIndex((c) => c.id === id);
  if (idx >= 0) {
    clients[idx] = { ...clients[idx], ...updates, lastUpdated: new Date().toISOString().slice(0, 10) };
    saveOSMClients(clients);
  }
}

export function deleteOSMClient(id: string): void {
  const clients = getOSMClients().filter((c) => c.id !== id);
  saveOSMClients(clients);
}
